"""Sentiment-driven pre-synthesized filler audio.

VADER classifies the user's input; a matching pre-recorded filler wav is
picked and played immediately at the start of a turn, masking LLM + TTS
latency. Wavs live in recordings/{positive,negative,neutral}/ and are
generated by make_filler_wavs.py (gitignored, so missing dirs disable the
feature per class).
"""
import random
import threading

import numpy as np
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

from .config import settings

_POS_THRESHOLD = 0.05
_NEG_THRESHOLD = -0.05

_analyzer = SentimentIntensityAnalyzer()
_lock = threading.Lock()
_cache: dict[str, list[np.ndarray] | None] = {}


def _wavs(sentiment: str) -> list[np.ndarray] | None:
    """Lazily load all wavs for a sentiment class; None if none available."""
    with _lock:
        if sentiment not in _cache:
            import soundfile as sf
            from pathlib import Path

            directory = Path(settings.RECORDINGS_DIR) / sentiment
            loaded = []
            if directory.is_dir():
                for path in sorted(directory.glob("*.wav")):
                    try:
                        audio, _ = sf.read(path, dtype="float32")
                        if len(audio):
                            loaded.append(audio)
                    except Exception:
                        continue
            _cache[sentiment] = loaded or None
        return _cache[sentiment]


def pick_filler(text: str) -> np.ndarray | None:
    """Return filler audio matched to the input's sentiment, or None."""
    text = (text or "").strip()
    if not text:
        return None
    try:
        compound = _analyzer.polarity_scores(text)["compound"]
    except Exception:
        return None
    sentiment = (
        "positive" if compound >= _POS_THRESHOLD
        else "negative" if compound <= _NEG_THRESHOLD
        else "neutral"
    )
    wavs = _wavs(sentiment)
    return random.choice(wavs) if wavs else None
